# Generated by Django 5.1.3 on 2024-12-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowNumber', models.IntegerField()),
                ('seatNumber', models.IntegerField()),
                ('isReserved', models.BooleanField(default=False)),
                ('bookedBy', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
